### ISSUE TITLE
Missing page number

### ISSUE THREAD

**Issue by asr** [afl-eafit/2018-1-lab1#4]
Please add the page number for the quotation

> The suffix automaton of a word x is defined as the minimal deterministic (non necessarily complete) automaton that recognizes the (finite) set of suffixes of x.

using the original version of the article.

**Comment by asr** [comment]
> using the original version of the article.

You didn't use the page number from the original version of the article.

**Comment by aortega0703** [comment]
By the original version of the article do you mean the book in which it appeared?

**Comment by asr** [comment]
Yes.
